steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch']
- name: 'gcr.io/cloud-builders/docker'
  args: ["pull", "gcr.io/$PROJECT_ID/url-to-pdf:latest"]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    "build",
    "-t", "gcr.io/$PROJECT_ID/$BRANCH_NAME/url-to-pdf:$COMMIT_SHA",
    "--cache-from", "gcr.io/$PROJECT_ID/url-to-pdf:latest",
    "."
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$BRANCH_NAME/url-to-pdf:$COMMIT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--no-promote', '--no-stop-previous-version']
  timeout: '600s'