steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    "build",
    "-t", "gcr.io/$PROJECT_ID/url-to-pdf:latest",
    "."
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/url-to-pdf:latest"]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--no-promote', '--no-stop-previous-version']
  timeout: '600s'